name: Create and publish a Docker image to GitHub Container Registry
on:
  push:
    tags:
      - 'server/**'
env:
  REGISTRY: ghcr.io
  # Name the image 'localful-server' not just 'localful' to be clearer.
  IMAGE_NAME: ${{ github.repository_owner }}/localful-server
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step will automatically tag the image will the git tag (e.g. v1.2.3 etc.)
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          # Strip 'server/' from the tag ref so docker image version is just the version
          tags: |
            type=match,pattern=server/(.*),group=1
            
      - name: Print
        run: |
          echo "${{ steps.docker_meta.outputs.tags }}"
          echo "${{ steps.docker_meta.outputs.labels }}"
#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          push: true
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
#
#      - name: Generate artifact attestation
#        uses: actions/attest-build-provenance@v1
#        with:
#          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#          subject-digest: ${{ steps.push.outputs.digest }}
#          push-to-registry: true
